[package]
name = "pollifier"
version = "0.1.0"
authors = ["Intrebute <ke.seas.feliz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_is_enum_variant = "0.1.1"